### PR TITLE
Add option to validate store file

### PR DESCRIPTION
**Pull request by bampakoa**
References #35

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think this should be implemented in https://github.com/sindresorhus/conf first so we don't have to read the file twice.

**Comment by bampakoa** [comment]
Yes, I thought of that. But then, isn't atomic writing care already about that?

**Comment by bampakoa** [comment]
@sindresorhus any thoughts on that?

**Comment by sindresorhus** [comment]
> But then, isn't atomic writing care already about that?

Sorry, I don't understand the question. Could you elaborate?

**Comment by sindresorhus** [comment]
> Since atomic file writing does not touch the original file (correct if I am wrong about that), it will not be corrupted during read from electron-store even if it is not a valid JSON file.

You are incorrect. Atomic file writing simply writes to a new file and then renames it (and overwrites) the destination file. The ensures there's no problem if the writing was interrupted. Clearing out the file on corrup JSON has nothing to do with this. It's Conf that detects a corrupt JSON and clears out the file.

**Comment by bampakoa** [comment]
Thanks for the clarification @sindresorhus . I am closing this PR and I will open a new one in the **conf** repo.

**Pull request closed without merging**
