### PR TITLE
Add store migrations

### LINKED ISSUE #19: Migrations
Would be useful to have forward migration support built-in. You define the version when something changed and a function where you can manipulate the store and the correct migrations will be applied according to the installed version on the first run after an update.

Quick braindump API:

```js
const Store = require('electron-store');

const migrations = {
	'1.0.0': store => {
		const old = store.get('old');
		store.set('new', old);
		store.delete('old');
	}
};

const store = new Store({migrations});
```

I'm open to feedback.

### PR DESCRIPTION
**Pull request by npezza93**
Enable migrations to be run whewn upgrading to particular versions

Fixes #19

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for working on this and sorry about the late review.

**Comment by sindresorhus** [comment]
Can you add some tests?

**Comment by sindresorhus** [comment]
Would be better to implement this in `conf`, so non-Electron project would benefit from the migrations feature too. You could just add a `projectVersion` option to `conf`.

**Comment by npezza93** [comment]
Yep I can do that @sindresorhus. Thanks for the review!

**Pull request closed without merging**
